import { Geist, Geist_Mono, Inter, Comic_Neue } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets:['latin']
});

const comic = Comic_Neue({
  subsets:['latin'], weight:['300', '400', '700']
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
